name: "BillWiz"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  stepper_counter_swipe: ^1.0.2
  provider: ^6.1.2
  printing: ^5.12.0
  pdf: ^3.11.0
  image_picker: ^1.1.2
  dotted_border: ^2.1.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1
flutter_icons:
  android: true
  
  image_path: "assets/images/APP_LOGO.png"
flutter:
  assets:
    - assets/images/
