import './Item.dart';

final List<Items> menuItems = [
  Items("Chow Mein", 80, 50, true),
  Items("Manchurian", 100, 60, true),
  Items("Veg Pulao", 90, 60, true),
  Items("Fried Rice", 100, 60, true),
  Items("Chilli Paneer", 150, 100, true),
  Items("Butter Dabeli", 30, null, false),
  Items("Veg Maggie", 70, null, false),
  Items("Peri-Peri French Fries", 100, null, false),
  Items("Pasta", 100, 60, true),
  Items("Cheese Sandwich", 120, null, false),
  Items("Pav Bhaji", 90, null, false),
  Items("Bottle", 20, null, false),
  Items("Extra Pav", 10, null, false),
  Items("Extra Bhaji", 70, 40, true),
  Items("Cheese Chow Mein", 120, 80, true),
  Items("Schezwan Chow Mein", 120, 80, true),
  Items("Noodle Manchurian", 120, 80, true),
  Items("Cheese Maggie", 100, null, false),
  Items("Paneer Pulao", 130, 80, true),
  Items("Shahi Pulao", 160, 100, true),
  Items("Jain Pulao", 120, 70, true),
  Items("Cheese Pulao", 140, 80, true),
  Items("Manchurian Rice", 140, 80, true),
  Items("Cheese Fried Rice", 140, 80, true),
  Items("Schezwan Rice", 120, 70, true),
  Items("Cheese Manchurian", 140, 80, true),
  Items("Cheese Paneer Chilli", 190, 120, true),
  Items("Veg Sandwich", 70, null, false),
  Items("Paneer Sandwich", 140, null, false),
  Items("Cheese Paneer Sandwich", 160, null, false),
  Items("Double Butter Dabeli", 60, null, false),
  Items("Paneer Dabeli", 60, null, false),
  Items("Schezwan Dabeli", 40, null, false),
  Items("Cheese French Fries", 130, null, false),
  Items("Cheese Pasta", 120, 70, true),
  Items("Double Butter Pav Bhaji", 140, null, false),
  Items("Khadi Pav Bhaji", 150, null, false),
  Items("Cheese Pav Bhaji", 140, null, false),
  Items("Shahi Pav Bhaji", 200, null, false),
  Items("Paneer Pav Bhaji", 150, null, false),
  Items("Jain Pav Bhaji", 150, null, false),
  Items("Extra Double Butter Pav", 30, null, false),
  Items("Cheese Pav", 50, null, false),
  Items("Butter Cube", 10, null, false),
];
