import './Item.dart';

final List<Items> menuItems = [
  Items("Chow Mein", 80, 50, true,'assets/images/chow_mein.png'),
  Items("Manchurian", 100, 60, true,'assets/images/manchurian.png'),
  Items("Veg Pulao", 90, 60, true,'assets/images/veg_pulao.png'),
  Items("Fried Rice", 100, 60, true,'assets/images/fried_rice.png'),
  Items("Chilli Paneer", 150, 100, true,'assets/images/chilli_paneer.png'),
  Items("Butter Dabeli", 30, null, false,'assets/images/bd.png'),
  Items("Veg Maggie", 70, null, false,'assets/images/vm.png'),
  Items("Peri-Peri French Fries", 100, null, false,'assets/images/ppff.png'),
  Items("Pasta", 100, 60, true,'assets/images/p.png'),
  Items("Cheese Sandwich", 120, null, false,'assets/images/cs.png'),
  Items("Pav Bhaji", 90, null, false,'assets/images/pb.png'),
  Items("Bottle", 20, null, false,'assets/images/b.png'),
  Items("Extra Pav", 10, null, false,'assets/images/ep.png'),
  Items("Extra Bhaji", 70, 40, true,'assets/images/eb.png'),
  Items("Cheese Chow Mein", 120, 80, true,'assets/images/ccm.png'),
  Items("Schezwan Chow Mein", 120, 80, true,'assets/images/scm.png'),
  Items("Noodle Manchurian", 120, 80, true,'assets/images/nm.png'),
  Items("Cheese Maggie", 100, null, false,'assets/images/cm.png'),
  Items("Paneer Pulao", 130, 80, true,'assets/images/pp.png'),
  Items("Shahi Pulao", 160, 100, true,'assets/images/sp.png'),
  Items("Jain Pulao", 120, 70, true,'assets/images/jp.png'),
  Items("Cheese Pulao", 140, 80, true,'assets/images/cp.png'),
  Items("Manchurian Rice", 140, 80, true,'assets/images/mr.png'),
  Items("Cheese Fried Rice", 140, 80, true,'assets/images/cfr.png'),
  Items("Schezwan Rice", 120, 70, true,'assets/images/sr.png'),
  Items("Cheese Manchurian", 140, 80, true,'assets/images/cman.png'),
  Items("Cheese Paneer Chilli", 190, 120, true,'assets/images/cpc.png'),
  Items("Veg Sandwich", 70, null, false,'assets/images/vs.png'),
  Items("Paneer Sandwich", 140, null, false,'assets/images/ps.png'),
  Items("Cheese Paneer Sandwich", 160, null, false,'assets/images/cps.png'),
  Items("Double Butter Dabeli", 60, null, false,'assets/images/dbd.png'),
  Items("Paneer Dabeli", 60, null, false,'assets/images/pd.png'),
  Items("Schezwan Dabeli", 40, null, false,'assets/images/sd.png'),
  Items("Cheese French Fries", 130, null, false,'assets/images/cff.png'),
  Items("Cheese Pasta", 120, 70, true,'assets/images/cpas.png'),
  Items("Double Butter Pav Bhaji", 140, null, false,'assets/images/dbpb.png'),
  Items("Khadi Pav Bhaji", 150, null, false,'assets/images/kpb.png'),
  Items("Cheese Pav Bhaji", 140, null, false,'assets/images/cpb.png'),
  Items("Shahi Pav Bhaji", 200, null, false,'assets/images/spb.png'),
  Items("Paneer Pav Bhaji", 150, null, false,'assets/images/ppb.png'),
  Items("Jain Pav Bhaji", 150, null, false,'assets/images/jpb.png'),
  Items("Extra Double Butter Pav", 30, null, false,'assets/images/edbp.png'),
  Items("Cheese Pav", 50, null, false,'assets/images/cpav.png'),
  Items("Butter Cube", 10, null, false,'assets/images/bc.png'),
];
